config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :login do
    get 'callback/new'
  end
  get 'login/new'

  get 'reports', to: 'reports#show'

  resources :accounts
  resources :goals
  resources :savings
  namespace :user do
    resource :preferences, only: [:update]
  end

  root 'reports#show'
end

app/models/saving.rb
# frozen_string_literal: true

class Saving < ApplicationRecord
  belongs_to :user
end

app/controllers/savings_controller.rb
# frozen_string_literal: true

class SavingsController < ApplicationController
  def index
    render locals_with_current_user({ savings: current_user.savings })
  end

  def new
    render locals_with_current_user({ saving: current_user.savings.build })
  end

  def edit
    render locals_with_current_user({ saving: current_user.savings.find(params[:id]) })
  end

  def create
    saving = current_user.savings.build(params.require(:saving).permit(:name, :amount))

    return redirect_to savings_path if saving.save

    render locals_with_current_user({ saving: })
  end

  def update
    saving = current_user.savings.find(params[:id])

    return redirect_to savings_path if saving.update(params.require(:saving).permit(:name, :amount))

    render locals_with_current_user({ saving: })
  end

  def destroy
    saving = current_user.savings.find(params[:id])

    return redirect_to savings_path if saving.destroy
  end
end

app/views/savings/_form.html.erb
<%= form_with model: saving, id: dom_id(saving)  do |f| %>
  <% if saving.errors.any? %>
    <ul>
      <% saving.errors.full_messages.each do |message|%>
        <li><%= message %> </li>
      <%end%>
    </ul>
  <%end%>
  <div>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :amount, "Amount" %>
    <%= f.number_field :amount, step: 0.01 %>
  </div>
  <%= f.submit %>
<% end %>

app/views/savings/_grid.html.erb
<%= savings.to_a %>

app/views/savings/_list.html.erb
<ul>
  <% savings.each do |saving| %>
    <li>
      <%= saving.name %> &mdash; <%= number_to_currency(saving.amount) %><br />
      <%= link_to "Edit", edit_saving_path(saving) %>
      <%= link_to "Delete", saving_path(saving), data: { turbo_method: :delete } %>
    </li>
  <% end %>
</ul>

app/views/savings/_saving.html.erb
<tr id="<%= dom_id(saving) %>" class="mdc-data-table__row">
  <th class="mdc-data-table__cell" scope="row"><%= saving.name %></th>
  <td class="mdc-data-table__cell mdc-data-table__cell--numeric"><%= number_to_currency(saving.amount, precision: 0) %></td>
  <td class="mdc-data-table__cell">
    <%= link_to "Edit", edit_saving_path(saving), data: { turbo_frame: :modal } %>
    <%= form_with model: saving, method: :delete, class: 'inline' do %>
      <button type="submit">Delete</button>
    <% end %>
  </td>
</tr>

app/views/savings/create.turbo_stream.erb
<%= turbo_stream.update(dom_id(saving), partial: 'form', locals: { saving:, current_user: }) %>

app/views/savings/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(saving) %>

app/views/savings/edit.html.erb
<%= render partial: 'form', locals: { saving:, current_user: } %>

app/views/savings/index.html.erb
<%= content_for :preferences_layout do %>
  <%= render partial: 'user/preferences/layout', locals: { current_user:, collection: :savings } %>
<% end %>
<div class="flex flex-col">
  <%= link_to new_saving_path do %>
    <md-filled-button label="New saving"></md-filled-button>
  <% end %>
  <div id="<%= dom_id(current_user, :savings) %>">
    <% if current_user.preferences.layout == "grid" %>
      <%= render partial: 'grid', locals: { savings: } %>
    <% else %>
      <%= render partial: 'list', locals: { savings: } %>
    <% end %>
  </div>
</div>

app/views/savings/new.html.erb
<%= render partial: 'form', locals: { saving:, current_user: } %>

app/views/savings/update.turbo_stream.erb
<%= turbo_stream.update(dom_id(saving), partial: 'form', locals: { saving:, current_user: }) %>