config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :login do
    get 'callback/new'
  end
  get 'login/new'

  get 'reports', to: 'reports#show'

  resources :accounts
  resources :goals
  resources :savings
  namespace :user do
    resource :preferences, only: [:update]
  end

  root 'reports#show'
end

app/models/goal.rb
# frozen_string_literal: true

class Goal < ApplicationRecord
  belongs_to :user

  validates :name, :amount, :target_date, presence: true
  validates :recurrance, presence: true, inclusion: %w[never monthly daily weekly yearly quarterly]

  def current_sinking_fund
    amount / BigDecimal(days_to_sink, 0) * days_elapsed
  end

  def days_remaining
    return BigDecimal(0, 0) if target_date <= Time.zone.today

    BigDecimal(target_date - Time.zone.today, 0)
  end

  def days_elapsed
    return BigDecimal(0, 0) if target_date <= Time.zone.today

    BigDecimal(Time.zone.today - previous_saving_date, 0)
  end

  private

  # rubocop:disable Metrics/MethodLength
  def days_to_sink
    target_date - previous_saving_date
  end

  def previous_saving_date
    case recurrance
    when 'daily'
      target_date.yesterday
    when 'weekly'
      target_date.last_week
    when 'monthly'
      target_date.last_month
    when 'yearly'
      target_date.last_year
    when 'quarterly'
      target_date.last_quarter
    else
      target_date
    end
  end

  def next_saving_date
    case recurrance
    when 'monthly'
      target_date.next_month
    when 'daily'
      target_date.tomorrow
    when 'weekly'
      target_date.next_week
    when 'yearly'
      target_date.next_year
    when 'quarterly'
      target_date.next_quarter
    else
      target_date
    end
  end
  # rubocop:enable Metrics/MethodLength
end

app/controllers/goals_controller.rb
# frozen_string_literal: true

class GoalsController < ApplicationController
  def index
    render locals_with_current_user({ goals: current_user.goals })
  end

  def new
    render locals_with_current_user({ goal: current_user.goals.build })
  end

  def edit
    render locals_with_current_user({ goal: current_user.goals.find(params[:id]) })
  end

  def create
    goal = current_user.goals.build(permitted_params)

    return redirect_to goals_path if goal.save

    render locals_with_current_user({ goal: })
  end

  def update
    goal = current_user.goals.find(params[:id])

    return redirect_to goals_path, notice: t('saved') if goal.update(permitted_params)

    render locals_with_current_user({ goal: })
  end

  def destroy
    goal = current_user.goals.find(params[:id])

    return redirect_to goals_path if goal.destroy
  end

  private

  def permitted_params
    params.require(:goal).permit(:name, :amount, :recurrance, :target_date, :start_date)
  end
end

app/views/goals/_form.html.erb
<%= form_with model: goal, id: dom_id(goal)  do |f| %>
  <% if goal.errors.any? %>
    <ul>
      <% goal.errors.full_messages.each do |message|%>
        <li><%= message %> </li>
      <%end%>
    </ul>
  <%end%>
  <div>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :amount, "Amount" %>
    <%= f.number_field :amount, step: 0.01 %>
  </div>
  <div>
    <%= f.label :recurrance, "Recurrance" %>
    <%= f.select :recurrance, %w[never daily weekly monthly quarterly yearly] %>
  </div>
  <div>
    <%= f.label :target_date, "Target date" %>
    <%= f.date_field :target_date %>
  </div>
  <%= f.submit %>
<% end %>

app/views/goals/_goal.html.erb
<tr id="<%= dom_id(goal) %>" class="mdc-data-table__row">
  <th class="mdc-data-table__cell" scope="row"><%= goal.name %></th>
  <td class="mdc-data-table__cell mdc-data-table__cell--numeric"><%= number_to_currency(goal.amount, precision: 0) %></td>
  <td class="mdc-data-table__cell"><%= goal.target_date %></td>
  <td class="mdc-data-table__cell"><%= goal.recurrance.capitalize %></td>
  <td class="mdc-data-table__cell mdc-data-table__cell--numeric"><%= number_to_currency(goal.accumlated_amount, precision: 2) %></td>
  <td class="mdc-data-table__cell">
    <%= link_to "Edit", edit_goal_path(goal), data: { turbo_frame: :modal } %>
    <%= form_with model: goal, method: :delete, class: 'inline' do %>
      <button type="submit">Delete</button>
    <% end %>
  </td>
</tr>

app/views/goals/_grid.html.erb
<%= goals.to_a %>

app/views/goals/_list.html.erb
<ul>
  <% goals.each do |goal| %>
    <li>
      <%= goal.name %> &mdash; <%= number_to_currency(goal.amount) %> &mdash; <%= goal.days_remaining %> &mdash; <%= goal.days_elapsed %> &mdash; <%= number_to_currency(goal.current_sinking_fund) %><br />
      <%= link_to "Edit", edit_goal_path(goal) %>
      <%= link_to "Delete", goal_path(goal), data: { turbo_method: :delete } %>
    </li>
  <% end %>
</ul>

app/views/goals/create.turbo_stream.erb
<%= turbo_stream.update(dom_id(goal), partial: 'form', locals: { goal:, current_user: }) %>

app/views/goals/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(goal) %>

app/views/goals/edit.html.erb
<%= render partial: 'form', locals: { goal:, current_user: } %>

app/views/goals/index.html.erb
<%= content_for :preferences_layout do %>
  <%= render partial: 'user/preferences/layout', locals: { current_user:, collection: :goals } %>
<% end %>
<div class="flex flex-col">
  <%= link_to new_goal_path do %>
    <md-filled-button label="New goal"></md-filled-button>
  <% end %>
  <div id="<%= dom_id(current_user, :goals) %>">
    <% if current_user.preferences.layout == "grid" %>
      <%= render partial: 'grid', locals: { goals: } %>
    <% else %>
      <%= render partial: 'list', locals: { goals: } %>
    <% end %>
  </div>
</div>

app/views/goals/new.html.erb
<%= render partial: 'form', locals: { goal:, current_user: } %>

app/views/goals/update.turbo_stream.erb
<%= turbo_stream.update(dom_id(goal), partial: 'form', locals: { goal:, current_user: }) %>