config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :login do
    get 'callback/new'
  end
  get 'login/new'

  get 'reports', to: 'reports#show'

  resources :accounts
  resources :goals
  resources :savings
  namespace :user do
    resource :preferences, only: [:update]
  end

  root 'reports#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="manifest" href="<%= url_for("/site.webmanifest") %>">
    <%= favicon_link_tag "apple-touch-icon.png", rel: "apple-touch-icon", sizes: "180x180" %>
    <%= favicon_link_tag "favicon-32x32.png", rel: "icon", sizes: "32x32", type: "image/png" %>
    <%= favicon_link_tag "favicon-16x16.png", rel: "icon", sizes: "16x16", type: "image/png" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@0;1&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <nav class="bg-slate-800">
      <div class="flex justify-between">
        <div class="flex h-14 items-center space-x-4 px-4">
          <%= navigation_link_to "Reports", reports_path %>
          <%= navigation_link_to "Accounts", accounts_path %>
          <%= navigation_link_to "Savings", savings_path %>
          <%= navigation_link_to "Goals", goals_path %>
        </div>
        <div class="flex h-14 items-center space-x-4 px-4">
          <%= yield :preferences_layout %>
        </div>
      </div>
    </nav>
    <main class="flex px-4 pt-4">
      <div class="relative">
        <% flash.each do |flash_type, message| %>
          <div class="fixed right-4 bg-slate-300 p-4 z-10" data-controller="flash" data-flash-target="message">
            <%= message %>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>