config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :login do
    get 'callback/new'
  end
  get 'login/new'

  get 'reports', to: 'reports#show'

  resources :accounts
  resources :goals
  resources :savings
  namespace :user do
    resource :preferences, only: [:update]
  end

  root 'reports#show'
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  belongs_to :user

  validates :name, :balance, presence: true

  scope :debts, -> { where(debt: true) }
  scope :not_debts, -> { where(debt: false) }
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  def index
    render locals_with_current_user({ accounts: current_user.accounts })
  end

  def new
    render locals_with_current_user({ account: current_user.accounts.build })
  end

  def edit
    render locals_with_current_user({ account: current_user.accounts.find(params[:id]) })
  end

  def create
    account = current_user.accounts.build(params.require(:account).permit(:name, :balance, :debt))

    return redirect_to accounts_path, notice: t('saved') if account.save

    render locals_with_current_user({ account: })
  end

  def update
    account = current_user.accounts.find(params[:id])

    if account.update(params.require(:account).permit(:name, :balance, :debt))
      return redirect_to accounts_path, notice: t('saved')
    end

    render locals_with_current_user({ account: })
  end

  def destroy
    account = current_user.accounts.find(params[:id])

    return redirect_to accounts_path if account.destroy
  end
end

app/views/accounts/_account.html.erb
<tr id="<%= dom_id(account) %>" class="mdc-data-table__row">
  <th class="mdc-data-table__cell" scope="row"><%= account.name %></th>
  <td class="mdc-data-table__cell mdc-data-table__cell--numeric"><%= number_to_currency(account.balance, precision: 0) %></td>
  <td class="mdc-data-table__cell"><%= account.debt %></td>
  <td class="mdc-data-table__cell">
    <%= link_to "Edit", edit_account_path(account), data: { turbo_frame: :modal } %>
    <%= form_with model: account, method: :delete, class: 'inline' do %>
      <button type="submit">Delete</button>
    <% end %>
  </td>
</tr>

app/views/accounts/_form.html.erb
<%= form_with model: account, id: dom_id(account)  do |f| %>
  <% if account.errors.any? %>
    <ul>
      <% account.errors.full_messages.each do |message|%>
        <li><%= message %> </li>
      <%end%>
    </ul>
  <%end%>
  <div>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :balance, "Balance" %>
    <%= f.number_field :balance, step: 0.01 %>
  </div>
  <%= f.button type: "submit" do %>
    <md-filled-button label="Save"></md-filled-button>
  <% end %>
<% end %>

app/views/accounts/_grid.html.erb
<%= accounts.to_a %>

app/views/accounts/_list.html.erb
<ul>
  <% accounts.each do |account| %>
    <li>
      <%= account.name %> &mdash; <%= number_to_currency(account.balance) %><br />
      <%= link_to "Edit", edit_account_path(account) %>
      <%= link_to "Delete", account_path(account), data: { turbo_method: :delete } %>
    </li>
  <% end %>
</ul>

app/views/accounts/create.turbo_stream.erb
<%= turbo_stream.replace(dom_id(account), partial: 'form', locals: { account:, current_user: }) %>

app/views/accounts/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(account) %>

app/views/accounts/edit.html.erb
<%= render partial: 'form', locals: { account:, current_user: } %>

app/views/accounts/index.html.erb
<%= content_for :preferences_layout do %>
  <%= render partial: 'user/preferences/layout', locals: { current_user:, collection: :accounts } %>
<% end %>
<div class="flex flex-col">
  <%= link_to new_account_path do %>
    <md-filled-button label="New account"></md-filled-button>
  <% end %>
  <div id="<%= dom_id(current_user, :accounts) %>">
    <% if current_user.preferences.layout == "grid" %>
      <%= render partial: 'grid', locals: { accounts: } %>
    <% else %>
      <%= render partial: 'list', locals: { accounts: } %>
    <% end %>
  </div>
</div>

app/views/accounts/new.html.erb
<%= form_with model: account do %>
    <%= %>
<% end %>

app/views/accounts/update.turbo_stream.erb
<%= turbo_stream.update(dom_id(account), partial: 'form', locals: { account:, current_user: }) %>